name: Deploy VNET ARM Template

# Trigger the workflow on every push to the main branch
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from your repository
    - name: Checkout source code
      uses: actions/checkout@v4

    # Step 2: Log into Azure using the secret created in Step 1
    - name: Log into Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_TEST_CONNECTION }}

    # Step 3: Deploy the ARM template
    - name: Deploy ARM Template
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: '0f5dca24-bf1b-4380-b31c-903a124598d9' # Replace with your sub ID tenant b17d20d7-121c-424f-9265-8991c246ef59
        resourceGroupName: 'Azure_TestRg_eus2' # Replace with your RG name
        template: ./vnettemplate.json # Path to your ARM template file
        parameters: ./vnetparameters.json 
        # Optional: uncomment below if you have a parameters file
